### 00 Test
GET http://localhost:5000

### 01 Signup
POST http://localhost:5000/signup
Content-Type: application/json

{
  "email": "praveen123@example.com",
  "password": "praveen123",
  "name": "Praveen"
}

### 02 Signup
POST http://localhost:5000/signin
Content-Type: application/json

{
  "email": "praveen123@example.com",
  "password": "praveen123"
}

### 03 Get All Products
GET http://localhost:5000/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmODkzNTZmNC1kODg1LTQ0ZDctOWYyZS04YTRjYWQ1YmFjYTYiLCJlbWFpbCI6InByYXZlZW4xMjNAZXhhbXBsZS5jb20iLCJpYXQiOjE3MjQ3NzcxNTEsImV4cCI6MTcyNDc4MDc1MX0.VjoSj3IScwM4D4-_PJBETYv1mpL6B9qXfSoXDgxThFI


### 04 setuser
GET http://localhost:5000/setuser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmODkzNTZmNC1kODg1LTQ0ZDctOWYyZS04YTRjYWQ1YmFjYTYiLCJlbWFpbCI6InByYXZlZW4xMjNAZXhhbXBsZS5jb20iLCJpYXQiOjE3MjQ4NjY4MjYsImV4cCI6MTcyNTQ3MTYyNn0.O9eCDNLb55QbXNAMGPbQGg7JIbMJglk8qJKTEOd7ufw


### 05 getuser
GET http://localhost:5000/getuser
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmODkzNTZmNC1kODg1LTQ0ZDctOWYyZS04YTRjYWQ1YmFjYTYiLCJlbWFpbCI6InByYXZlZW4xMjNAZXhhbXBsZS5jb20iLCJpYXQiOjE3MjQ4NjY4MjYsImV4cCI6MTcyNTQ3MTYyNn0.O9eCDNLb55QbXNAMGPbQGg7JIbMJglk8qJKTEOd7ufw