### 00 Home -> Test 
GET http://localhost:5000

###### Authentication ######

### 01 Signup
POST http://localhost:5000/auth/signup
Content-Type: application/json

{
    "firstName": "Praveen",
    "lastName": "Ande",
    "email": "praveenande1@example.com",
    "password":"praveenande123"
}

### 02 Signin
POST http://localhost:5000/auth/signin
Content-Type: application/json

{
  "email": "praveenande@example.com",
  "password": "praveenande123"
}

###############

### 03 Get All Products -> without authMiddleware
GET http://localhost:5000/products1

###############

### 04 Get All Products -> with authMiddleware -> Authorization header
GET http://localhost:5000/products2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMDE5NjM2Yi1lNDRlLTQwZTMtYWI2Yi05ODgyNDExMjFhMTciLCJpYXQiOjE3MjY3NTk3NTQsImV4cCI6MTcyNzM2NDU1NH0.KnUsDeLwPXf8AQFrKCCTbkPL8YlSjVxK3eg-GX6oMyw


### 05 setuser
GET http://localhost:5000/setuser

### 06 getuser
GET http://localhost:5000/getuser

###############

### 07 Get All Products -> with authMiddleware -> From CookieStorage
GET http://localhost:5000/products3
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMDE5NjM2Yi1lNDRlLTQwZTMtYWI2Yi05ODgyNDExMjFhMTciLCJpYXQiOjE3MjY3NjMxMjQsImV4cCI6MTcyNzM2NzkyNH0.hJIpnDEZ1ZghDXitvzSLhqAbHl3xvXEhJN9J2NDqeak

################

### 08 Signout
GET http://localhost:5000/signout
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMDE5NjM2Yi1lNDRlLTQwZTMtYWI2Yi05ODgyNDExMjFhMTciLCJpYXQiOjE3MjY3NjMxMjQsImV4cCI6MTcyNzM2NzkyNH0.hJIpnDEZ1ZghDXitvzSLhqAbHl3xvXEhJN9J2NDqeak

################