### 00 Home
GET http://localhost:5000/

### 01 Error
GET http://localhost:5000/error


### 02 next
GET http://localhost:5000/next

### 03 user
GET http://localhost:5000/user

### 04 customer
GET http://localhost:5000/customer