###### Authentication ######

### 01 Signup
POST http://localhost:5000/api/v1/auth/signup
Content-Type: application/json

{
    "firstName": "Praveen",
    "lastName": "Ande",
    "email": "praveen12345@example.com",
    "password":"praveen12345",
    "roleId":"55e958ba-8b6d-460b-aaf7-8d200868e434"
}

### 02 Signin
POST http://localhost:5000/api/v1/auth/signin
Content-Type: application/json

{
  "email": "praveen12345@example.com",
  "password": "praveen12345"
}

### 03 Signout

@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMWVjYTk0Ny1hZGFlLTQ5MWEtYWM1MC03YjU2NzNjZTVmNTQiLCJpYXQiOjE3MzE5MDQyNTYsImV4cCI6MTczMjUwOTA1Nn0.RXgHiv2NrZ0WtVdSKeqYDRI9jN5cj3m6E0cG2ek8AhE
GET http://localhost:5000/api/v1/auth/signout
Cookie: refreshToken={{refreshToken}}
