### 00 Home -> Test 
GET http://localhost:5000


###### Authentication ######

### 01 Signup
POST http://localhost:5000/api/v1/auth/signup
Content-Type: application/json

{
    "firstName": "",
    "lastName": "",
    "email": "praveenanddes@example.com",
    "password":"praveenande123",
    "roleId":"c1f8b534-cf5b-4d39-be98-6ce19aa3e6bf"
}

### 02 Signin
POST http://localhost:5000/api/v1/auth/signin
Content-Type: application/json

{
  "email": "praveenande@example.com",
  "password": "praveenande123"
}

### 03 Signout
GET http://localhost:5000/api/v1/signout
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMDE5NjM2Yi1lNDRlLTQwZTMtYWI2Yi05ODgyNDExMjFhMTciLCJpYXQiOjE3MjY3NjMxMjQsImV4cCI6MTcyNzM2NzkyNH0.hJIpnDEZ1ZghDXitvzSLhqAbHl3xvXEhJN9J2NDqeak


### 01 Get All Products -> Success -> token
GET http://localhost:5000/api/v1/products1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwYjA4NWZhMi0yZDg0LTRiZjItODUyNy1mZmQ5MGI2ZWM1NTIiLCJpYXQiOjE3Mjc2NzkwNzUsImV4cCI6MTcyODI4Mzg3NX0.6sGGSejaGnlhpLaxiIF9IRJydYaex4X13r9Ql_X-Bwo

### 01 Get All Products -> Success -> Cookie
GET http://localhost:5000/api/v1/products1
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTU2Njg1NC1mMTI5LTRlNzQtODgyNi1mMzA3YmE2YzQ1YTEiLCJpYXQiOjE3Mjc2NzYwNDEsImV4cCI6MTcyODI4MDg0MX0.Ex9UIEHYOQTLxf1nNR_RSCzYS2M6Cnbny4ZM3sC50uU

### 02 Get All Products -> Failure
GET http://localhost:5000/api/v1/products2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMDE5NjM2Yi1lNDRlLTQwZTMtYWI2Yi05ODgyNDExMjFhMTciLCJpYXQiOjE3MjY3NjMxMjQsImV4cCI6MTcyNzM2NzkyNH0.hJIpnDEZ1ZghDXitvzSLhqAbHl3xvXEhJN9J2NDqeak

### 02 Get All Products -> Failure
GET http://localhost:5000/api/v1/products2
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTU2Njg1NC1mMTI5LTRlNzQtODgyNi1mMzA3YmE2YzQ1YTEiLCJpYXQiOjE3Mjc2NzYwNDEsImV4cCI6MTcyODI4MDg0MX0.Ex9UIEHYOQTLxf1nNR_RSCzYS2M6Cnbny4ZM3sC50uU


########## NotFound ############
GET http://localhost:5000/api/v1/notfound


####### Query Params ##########

### Test 1: Default Pagination
GET http://localhost:5000/api/v1/products

### Test 2: Specify Page 1 with 5 items (default 10 items)  per page
GET http://localhost:5000/api/v1/products?page=1&limit=5

### Test 3: Page 2 with 5 items per page
GET http://localhost:5000/api/v1/products?page=2&limit=5

### Test 4: Page 3 with 5 items per page
GET http://localhost:5000/api/v1/products?page=3&limit=5

### Test 5: Attempt to get a page beyond total pages
GET http://localhost:5000/api/v1/products?page=100&limit=5

### Test 6: Use a large limit
GET http://localhost:5000/api/v1/products?page=1&limit=50

### Test 7: Attempt to use a limit beyond the maximum
GET http://localhost:5000/api/v1/products?page=1&limit=200

### Test 8: Use pagination with search
GET http://localhost:5000/api/v1/products?page=1&limit=10&search=phone

### Test 9: Use pagination with sorting
GET http://localhost:5000/api/v1/products?page=1&limit=10&sort=price:desc

### Test 10: Combine pagination, search, and sorting
GET http://localhost:5000/api/v1/products?page=1&limit=10&search=laptop&sort=price:asc

##########################

### 01 Get All Products
GET http://localhost:5000/api/v1/api/v1/products

### 02 Create New Product
POST http://localhost:5000/api/v1/api/v1/products
Content-Type: application/json

{
  "name": "New Products2",
  "price": 19.99
}

### 03 Update Product (Full Update)
PUT http://localhost:5000/api/v1/products/7c0164ec-a20b-4c77-b461-8704c0887712
Content-Type: application/json

{
  "name": "Updated Product",
  "price": 25.99
}

### 04 Patch Product (Partial Update)
PATCH http://localhost:5000/api/v1/products/7c0164ec-a20b-4c77-b461-8704c0887712
Content-Type: application/json

{
  "price": 29.99
}

### 05 Soft Delete Product
DELETE http://localhost:5000/api/v1/products/7c0164ec-a20b-4c77-b461-8704c0887712